site_name: learningOrchestra Docs
nav:
  - Home: index.md
  - About: about.md
  - Install and deploy: install.md
  - Use:
    - Description of the microservices: microservices.md
    - REST APIs: rest-apis.md
    - Python package: python-package.md
  - Get support: support.md
theme:
  name: readthedocs
  features:
    - instant
    - search.highlight
  plugins:
    - search
